SET SQL_SAFE_UPDATES = 0;

INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Stanislav', 'Cherchesov', '1');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Juan', 'Antonio Pizzi', '2');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Hector', 'Cuper', '3');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Oscar', 'Washington Tabarez', '4');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Fernando', 'Santos', '5');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Julen', 'Lopetegui', '6');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Herve', 'Renard', '7');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Carlos', 'Queiroz', '8');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Didier', 'Deschamps', '9');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Bert', 'Van Marwijk', '10');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Ricardo', 'Gareca', '11');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Age', 'Hareide', '12');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Jorge', 'Sampaoli', '13');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Heimir', 'Hallgrimsson', '14');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Zlatko', 'Dalic', '15');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Gernot', 'Rohr', '16');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Tite', '', '17');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Vladimir', 'Petkovic', '18');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Oscar', 'Ramirez', '19');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Mladen', 'Krstajic', '20');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Joachim', 'Low', '21');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Juan', 'Carlos Osorio', '22');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Janne', 'Andersson', '23');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Shin', 'Tae-Yong', '24');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Roberto', 'Martinez', '25');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Hernan', 'Dario Gomez', '26');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Nabil', 'Maaloul', '27');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Gareth', 'Southgate', '28');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Adam', 'Nawalka', '29');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Aliou', 'Cisse', '30');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Jose', 'Pekerman', '31');
INSERT INTO `world_cup`.`manager` (`l_name`, `f_name`, `team_id`) VALUES ('Arika', 'Nishino', '32');

SET SQL_SAFE_UPDATES = 1;