const schedule = {
    matches: [
           {
                "id": 1,
                "type": "GR",
                "round": 1,
                "date": 14,
                "month": 6,
                "localTime": "15:00",
                "team1": "Russia",
                "team2": "Saudi Arabia",
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 2,
                "type": "GR",
                "round": 1,
                "date": 15,
                "month": 6,
                "localTime": "12:00",
                "team1": "Egypt",
                "team2": "Uruguay",
                "stadium": "Ekaterinburg Arena",
                "result": "0-0"
            },
            {
                "id": 3,
                "type": "GR",
                "round": 1,
                "date": 15,
                "month": 6,
                "localTime": "15:00",
                "team1": "Marocco",
                "team2": "Iran",
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 4,
                "type": "GR",
                "round": 1,
                "date": 15,
                "month": 6,
                "localTime": "18:00",
                "team1": "Portugal",
                "team2": "Spain",
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 5,
                "type": "GR",
                "round": 1,
                "date": 16,
                "month": 6,
                "localTime": "10:00",
                "team1": "France",
                "team2": "Australia",
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 6,
                "type": "GR",
                "round": 1,
                "date": 16,
                "month": 6,
                "localTime": "13:00",
                "team1": "Argentina",
                "team2": "Iceland",
                "stadium": "Spartak Stadium",
                "result": "0-0"
            },
            {
                "id": 7,
                "type": "GR",
                "round": 1,
                "date": 16,
                "month": 6,
                "localTime": "16:00",
                "team1": "Peru",
                "team2": "Denmark",
                "stadium": "Mordovia Arena",
                "result": "0-0"
            },
            {
                "id": 8,
                "type": "GR",
                "round": 1,
                "date": 16,
                "month": 6,
                "localTime": "19:00",
                "team1": "Croatia",
                "team2": "Nigeria",
                "stadium": "Kaliningrad Stadium",
                "result": "0-0"
            },
            {
                "id": 9,
                "type": "GR",
                "round": 1,
                "date": 17,
                "month": 6,
                "localTime": "12:00",
                "team1": "Costa Rica",
                "team2": "Serbia",
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 10,
                "type": "GR",
                "round": 1,
                "date": 17,
                "month": 6,
                "localTime": "15:00",
                "team1": "Germany",
                "team2": "Serbia",
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 11,
                "type": "GR",
                "round": 1,
                "date": 17,
                "month": 6,
                "localTime": "18:00",
                "team1": "Brazil",
                "team2": "Switzerland",
                "stadium": "Rostov Arena",
                "result": "0-0"
            },
            {
                "id": 12,
                "type": "GR",
                "round": 1,
                "date": 18,
                "month": 6,
                "localTime": "12:00",
                "team1": "Sweden",
                "team2": "South Korea",
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 13,
                "type": "GR",
                "round": 1,
                "date": 18,
                "month": 6,
                "localTime": "15:00",
                "team1": "Belgium",
                "team2": "Panama",
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 14,
                "type": "GR",
                "round": 1,
                "date": 18,
                "month": 6,
                "localTime": "18:00",
                "team1": "England",
                "team2": "Tunisia",
                "stadium": "Volgograd Arena",
                "result": "0-0"
            },
            {
                "id": 15,
                "type": "GR",
                "round": 1,
                "date": 19,
                "month": 6,
                "localTime": "12:00",
                "team1": "Japan",
                "team2": "Colombia",
                "stadium": "Mordovia Arena",
                "result": "0-0"
            },
            {
                "id": 16,
                "type": "GR",
                "round": 1,
                "date": 19,
                "month": 6,
                "localTime": "15:00",
                "team1": "Poland",
                "team2": "Senegal",
                "stadium": "Spartak Stadium",
                "result": "0-0"
            },
            {
                "id": 17,
                "type": "GR",
                "round": 2,
                "date": 19,
                "month": 6,
                "localTime": "18:00",
                "team1": "Russia",
                "team2": "Egypt",
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 18,
                "type": "GR",
                "round": 2,
                "date": 20,
                "month": 6,
                "localTime": "12:00",
                "team1": "Portugal",
                "team2": "Marocco",
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 19,
                "type": "GR",
                "round": 2,
                "date": 20,
                "month": 6,
                "localTime": "15:00",
                "team1": "Saudi Arabia",
                "team2": "Uruguay",
                "stadium": "Rostov Arena",
                "result": "0-0"
            },
            {
                "id": 20,
                "type": "GR",
                "round": 2,
                "date": 20,
                "month": 6,
                "localTime": "18:00",
                "team1": "Spain",
                "team2": "Iran",
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 21,
                "type": "GR",
                "round": 2,
                "date": 21,
                "month": 6,
                "localTime": "12:00",
                "team1": "Australia",
                "team2": "Denmark",
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 22,
                "type": "GR",
                "round": 2,
                "date": 21,
                "month": 6,
                "localTime": "15:00",
                "team1": "France",
                "team2": "Peru",
                "stadium": "Ekaterinburg Arena",
                "result": "0-0"
            },
            {
                "id": 23,
                "type": "GR",
                "round": 2,
                "date": 21,
                "month": 6,
                "localTime": "18:00",
                "team1": "Argentina",
                "team2": "Croatia",
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 24,
                "type": "GR",
                "round": 2,
                "date": 22,
                "month": 6,
                "localTime": "12:00",
                "team1": "Brazil",
                "team2": "Costa Rica",
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 25,
                "type": "GR",
                "round": 2,
                "date": 22,
                "month": 6,
                "localTime": "15:00",
                "team1": "Iceland",
                "team2": "Nigeria",
                "stadium": "Volgograd Arena",
                "result": "0-0"
            },
            {
                "id": 26,
                "type": "GR",
                "round": 2,
                "date": 22,
                "month": 6,
                "localTime": "18:00",
                "team1": "Switzerland",
                "team2": "Serbia",
                "stadium": "Kaliningrad Stadium",
                "result": "0-0"
            },
            {
                "id": 27,
                "type": "GR",
                "round": 2,
                "date": 23,
                "month": 6,
                "localTime": "12:00",
                "team1": "Belgium",
                "team2": "Tunisia",
                "stadium": "Spartak Stadium",
                "result": "0-0"
            },
            {
                "id": 28,
                "type": "GR",
                "round": 2,
                "date": 23,
                "month": 6,
                "localTime": "15:00",
                "team1": "Mexico",
                "team2": "South Korea",
                "stadium": "Rostov Arena",
                "result": "0-0"
            },
            {
                "id": 29,
                "type": "GR",
                "round": 2,
                "date": 23,
                "month": 6,
                "localTime": "18:00",
                "team1": "Germany",
                "team2": "Sweden",
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 30,
                "type": "GR",
                "round": 2,
                "date": 24,
                "month": 6,
                "localTime": "12:00",
                "team1": "England",
                "team2": "Panama",
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 31,
                "type": "GR",
                "round": 2,
                "date": 24,
                "month": 6,
                "localTime": "15:00",
                "team1": "Senegal",
                "team2": "Japan",
                "stadium": "Ekaterinburg Arena",
                "result": "0-0"
            },
            {
                "id": 32,
                "type": "GR",
                "round": 2,
                "date": 24,
                "month": 6,
                "localTime": "18:00",
                "team1": "Poland",
                "team2": "Colombia",
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 33,
                "type": "GR",
                "round": 3,
                "date": 25,
                "month": 6,
                "localTime": "14:00",
                "team1": "Russia",
                "team2": "Uruguay",
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 34,
                "type": "GR",
                "round": 3,
                "date": 25,
                "month": 6,
                "localTime": "14:00",
                "team1": "Egypt",
                "team2": "Saudi Arabia",
                "stadium": "Volgograd Arena",
                "result": "0-0"
            },
            {
                "id": 35,
                "type": "GR",
                "round": 3,
                "date": 25,
                "month": 6,
                "localTime": "18:00",
                "team1": "Spain",
                "team2": "Marocco",
                "stadium": "Kaliningrad Stadium",
                "result": "0-0"
            },
            {
                "id": 36,
                "type": "GR",
                "round": 3,
                "date": 25,
                "month": 6,
                "localTime": "18:00",
                "team1": "Portugal",
                "team2": "Iran",
                "stadium": "Mordovia Arena",
                "result": "0-0"
            },
            {
                "id": 37,
                "type": "GR",
                "round": 3,
                "date": 26,
                "month": 6,
                "localTime": "14:00",
                "team1": "France",
                "team2": "Denmark",
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 38,
                "type": "GR",
                "round": 3,
                "date": 26,
                "month": 6,
                "localTime": "14:00",
                "team1": "Australia",
                "team2": "Peru",
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 39,
                "type": "GR",
                "round": 3,
                "date": 26,
                "month": 6,
                "localTime": "18:00",
                "team1": "Iceland",
                "team2": "Croatia",
                "stadium": "Rostov Arena",
                "result": "0-0"
            },
            {
                "id": 40,
                "type": "GR",
                "round": 3,
                "date": 26,
                "month": 6,
                "localTime": "18:00",
                "team1": "Argentina",
                "team2": "Nigeria",
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 41,
                "type": "GR",
                "round": 3,
                "date": 27,
                "month": 6,
                "localTime": "14:00",
                "team1": "Mexico",
                "team2": "Sweden",
                "stadium": "Ekaterinburg Arena",
                "result": "0-0"
            },
            {
                "id": 42,
                "type": "GR",
                "round": 3,
                "date": 27,
                "month": 6,
                "localTime": "14:00",
                "team1": "South Korea",
                "team2": "Germany",
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 43,
                "type": "GR",
                "round": 3,
                "date": 27,
                "month": 6,
                "localTime": "18:00",
                "team1": "Brazil",
                "team2": "Serbia",
                "stadium": "Spartak Stadium",
                "result": "0-0"
            },
            {
                "id": 44,
                "type": "GR",
                "round": 3,
                "date": 27,
                "month": 6,
                "localTime": "18:00",
                "team1": "Switzerland",
                "team2": "Costa Rica",
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 45,
                "type": "GR",
                "round": 3,
                "date": 28,
                "month": 6,
                "localTime": "14:00",
                "team1": "Poland",
                "team2": "Japan",
                "stadium": "Volgograd Arena",
                "result": "0-0"
            },
            {
                "id": 46,
                "type": "GR",
                "round": 3,
                "date": 28,
                "month": 6,
                "localTime": "14:00",
                "team1": "Senegal",
                "team2": "Colombia",
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 47,
                "type": "GR",
                "round": 3,
                "date": 28,
                "month": 6,
                "localTime": "18:00",
                "team1": "England",
                "team2": "Belgium",
                "stadium": "Kaliningrad Stadium",
                "result": "0-0"
            },
            {
                "id": 48,
                "type": "GR",
                "round": 3,
                "date": 28,
                "month": 6,
                "localTime": "18:00",
                "team1": "Tunisia",
                "team2": "Panama",
                "stadium": "Mordovia Arena",
                "result": "0-0"
            },
            {
                "id": 49,
                "type": "R16",
                "round": 4,
                "date": 30,
                "month": 6,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 50,
                "type": "R16",
                "round": 4,
                "date": 30,
                "month": 6,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 51,
                "type": "R16",
                "round": 4,
                "date": 1,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 52,
                "type": "R16",
                "round": 4,
                "date": 1,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 53,
                "type": "R16",
                "round": 4,
                "date": 2,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 54,
                "type": "R16",
                "round": 4,
                "date": 2,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Rostov Arena",
                "result": "0-0"
            },
            {
                "id": 55,
                "type": "R16",
                "round": 4,
                "date": 3,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 56,
                "type": "R16",
                "round": 4,
                "date": 3,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Spartak Stadium",
                "result": "0-0"
            },
            {
                "id": 57,
                "type": "QT",
                "round": 5,
                "date": 6,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Nizhny Novgorod Stadium",
                "result": "0-0"
            },
            {
                "id": 58,
                "type": "QT",
                "round": 5,
                "date": 6,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Kazan Arena",
                "result": "0-0"
            },
            {
                "id": 59,
                "type": "QT",
                "round": 5,
                "date": 7,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Samara Arena",
                "result": "0-0"
            },
            {
                "id": 60,
                "type": "QT",
                "round": 5,
                "date": 7,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Fisht Stadium",
                "result": "0-0"
            },
            {
                "id": 61,
                "type": "SF",
                "round": 6,
                "date": 10,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 62,
                "type": "SF",
                "round": 6,
                "date": 11,
                "month": 7,
                "localTime": "18:00",
                "team1": null,
                "team2": null,
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            },
            {
                "id": 63,
                "type": "T3",
                "round": 7,
                "date": 14,
                "month": 7,
                "localTime": "14:00",
                "team1": null,
                "team2": null,
                "stadium": "Saint Petersburg Stadium",
                "result": "0-0"
            },
            {
                "id": 64,
                "type": "FN",
                "round": 7,
                "date": 15,
                "month": 7,
                "localTime": "15:00",
                "team1": null,
                "team2": null,
                "stadium": "Luzhniki Stadium",
                "result": "0-0"
            }
        ]
    }

    function parse(something) {
    const array = something.matches.map((data, index)=>{
        console.log(`INSERT INTO \`world_cup\`.\`schedule\` (\`type\`, \`round\`, \`date\`, \`month\`, \`localtime\`, \`home_id\`, \`away_id\`, \`stadium_id\`, \`home_score\`, \`away_score\`) VALUES (\'${data.type}\', \'${data.round}\', \'${data.date}\', \'${data.month}\', \'${data.localTime}\', \'${data.team1}\', \'${data.team2}\', \'${data.stadium}\', \'0\', \'0\')\;`);
    });
}

parse(schedule);
